### ISSUE TITLE
Issues with AmrPlusPlus pipleine with latest version of SNP

### ISSUE THREAD

**Issue by CarstenBaker** [Isabella136/AmrPlusPlus_SNP#27]
I have run into an issue using the latest version of SNP with Amrplusplus pipeline, posted the issue here :  https://github.com/Microbial-Ecology-Group/AMRplusplus/issues/21

The latest version of SNP seems to rely on Python >3.9 but the singularity container used in AmrPlusPlus pipeline (v3.0.2) currently only uses Python 3.7 so if I run the test command 
```
nextflow run main_AMR++.nf -profile singularity --snp Y
```
I get this error which seems to be an issue with the version of Python
```
  File "SNP_Verification.py", line 275
    with (open(config['FULL_FILE_NAMES']['NTYPE_OUTPUT'], "w") as outputN,
                                                                ^
SyntaxError: invalid syntax
```

Is there a version of SNP designed specifically for this pipeline ? Couldn't see any version numbers on SNP so not sure if I am missing something obvious ?

**Comment by Isabella136** [comment]
I'm getting the same issue as well, so you're not doing anything wrong.

On the original issue posted in the AMRplusplus repo, I made a comment to the person in charge of maintaining the Singularity container to see if they can update it. If he can't, then I can create another version of the SNP Verification program that should be compatible.

**Comment by Isabella136** [comment]
In the meantime, I do know that if anaconda is installed on your computer, you can install mamba and use the conda profile. The v3.0.2 release of AMR++ does work with SNP Verification, so you shouldn't run into any problem

**Comment by CarstenBaker** [comment]
We have been running it on a HPC system so trying to stick to the original pipeline as closely as possible to make it easy to reproduce. We were discussing whether to use conda (although having the singularity images stored in 1 location is nice) or adapting the pipeline to create a separate singularity container for SNP with all the dependencies installed to avoid touching the AMRplusplus container (although this might break the pipeline for updates).

For the moment the conda route should be easiest until the pipeline can be updated/adapted, just knowing I wasn't missing an obvious fix is a great help. Nothing worse than spending a week creating a solution to a problem that doesn't exist !!

Thanks for the response.
