### ISSUE TITLE
Standalon running - incomplete results

### ISSUE THREAD

**Issue by gustavogregoracci** [Isabella136/AmrPlusPlus_SNP#29]
Dear Natalie,
Sorry to bother you again. Your new congif.ini file solved our run issues and we've been able to apply it to our samples. We have hundreds of alignment matches against Megares in sam files, dozens of which require SNP confirmation. But when we run your script, our results file come back with ~15 evaluations only. I suppose the genes that do not require SNP confirmation would be ignored, but I was expecting that all which require SNP confirmation would be evaluated. Any thoughts on why not? Any files we could share to improve understanding? 
Thanks for you time!

**Comment by Isabella136** [comment]
Can you share an example of a sam file and its results?

**Comment by gustavogregoracci** [comment]
Many apologies for thte delay. End of semester hit hard. :)
Please, try to see the files in this link: https://drive.google.com/drive/folders/1dbXyFeR2b4Z2GUuuYlmW515jHm8iezv-?usp=sharing

**Comment by Isabella136** [comment]
I don't have access to the files; do you want me to send a request for access through Google Drive?

**Comment by gustavogregoracci** [comment]
Please

**Comment by Isabella136** [comment]
I'm confused; what is the problem exactly?

**Comment by gustavogregoracci** [comment]
So, our alignment against Megares provided thousands of hits. Disregarding the ones that did not require SNP confirmation, shouldn't all other be tested? It would still be up to hundreds or perhaps thousands, but we get only 15 results back. Could you try to explain to me?

**Comment by Isabella136** [comment]
All of them are tested, but most of the alignments didn't contain any of the key nucleotides or amino acids required for resistance, so they come back as susceptible

**Comment by gustavogregoracci** [comment]
But the totals don't seem to match. Shouldn't they? It seems AMR++_SNP returns way fewer sequences...

**Comment by gustavogregoracci** [comment]
Or perhaps they do. The normal genes are indeed abundant.

**Comment by Isabella136** [comment]
They should only return alignments that have been confirmed as resistant. To explain it a bit more clearly, lets take a random reference, gene A, which has been aligned to 200 query sequence in a sample:

- If all of the 200 alignments have been marked as susceptible, then gene A will be marked as having 0 resistant reads
- If only one alignment has been marked as resistant, then gene A will be marked as having 1 resistant read
- If 100 alignments have been marked as resistant, gene A will be marked as having 100 resistant reads
- If all 200 alignments have been marked as resistant, then gene A will be marked as having 200 resistant reads
